language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

os: linux
dist: xenial
jdk: openjdk11
services:
  - postgresql
  - redis

before-install:
  - psql -c 'CREATE DATABASE draft;' -U postgres
  - psql -c "CREATE USER draft PASSWORD 'draft-pw';"
  - psql -d draft -c "CREATE EXTENSION postgis;"
  - psql -d draft -c "CREATE EXTENSION postgis_raster;"
  - psql -d draft -c "CREATE EXTENSION postgis_topology;"
  - psql -d draft -c "CREATE EXTENSION postgis_sfcgal;"
  - psql -d draft -c "CREATE EXTENSION fuzzystrmatch;"
  - psql -d draft -c "CREATE EXTENSION address_standardizer;"
  - psql -d draft -c "CREATE EXTENSION address_standardizer_data_us;"
  - psql -d draft -c "CREATE EXTENSION postgis_tiger_geocoder;"

install:
  - ./gradlew assemble

script:
  - ./gradlew clean build
