language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

os: linux
dist: xenial
jdk: openjdk11
services:
  - postgresql
  - redis
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before-install:
  - psql -c 'CREATE DATABASE draft;' -U postgres
  - psql -c "CREATE USER draft PASSWORD 'draft-pw';"

install:
  - ./gradlew assemble

before_script:
  - psql -d draft -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION postgis_raster;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION postgis_topology;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION postgis_sfcgal;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION fuzzystrmatch;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION address_standardizer;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION address_standardizer_data_us;' -U postgres
  - psql -d draft -c 'CREATE EXTENSION postgis_tiger_geocoder;' -U postgres

script:
  - ./gradlew clean build
