spring:
  profiles: local
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/draft?serverTimezone=UTC
    username: draft
    password: draft-pw
    initialization-mode: always
    data:
      - classpath:emd1.sql
      - classpath:emd2.sql
